config/routes.rb
Synphony::Application.routes.draw do
  resources :api_keys

  namespace :api, defaults: { format: 'json' } do
    namespace :simplified do
      resource :login
      resources :projects
      resources :projects do
        resources :words
      end
    end

    namespace :v1 do
    end
  end

  resources :user_language_projects

  resources :language_projects

  resources :language_projects do
    resources :user_spelling_patterns
    resources :sequence_spelling_patterns
    resources :sequences
    resources :sentence_spelling_patterns
    resources :sentence_words
    resources :sentences
    resources :word_spelling_patterns
    resources :words
    resources :spelling_patterns
    resources :phonemes
    resources :graphemes
  end

  devise_for :users

  root :to => 'landing_page#index'

end

app/models/sentence_word.rb
class SentenceWord < ActiveRecord::Base
  belongs_to :word
  belongs_to :sentence
  attr_accessible :position
end

app/controllers/sentence_words_controller.rb
class SentenceWordsController < ApplicationController
  # GET /sentence_words
  # GET /sentence_words.json
  def index
    @sentence_words = SentenceWord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sentence_words }
    end
  end

  # GET /sentence_words/1
  # GET /sentence_words/1.json
  def show
    @sentence_word = SentenceWord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sentence_word }
    end
  end

  # GET /sentence_words/new
  # GET /sentence_words/new.json
  def new
    @sentence_word = SentenceWord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sentence_word }
    end
  end

  # GET /sentence_words/1/edit
  def edit
    @sentence_word = SentenceWord.find(params[:id])
  end

  # POST /sentence_words
  # POST /sentence_words.json
  def create
    @sentence_word = SentenceWord.new(params[:sentence_word])

    respond_to do |format|
      if @sentence_word.save
        format.html { redirect_to @sentence_word, notice: 'Sentence word was successfully created.' }
        format.json { render json: @sentence_word, status: :created, location: @sentence_word }
      else
        format.html { render action: "new" }
        format.json { render json: @sentence_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sentence_words/1
  # PUT /sentence_words/1.json
  def update
    @sentence_word = SentenceWord.find(params[:id])

    respond_to do |format|
      if @sentence_word.update_attributes(params[:sentence_word])
        format.html { redirect_to @sentence_word, notice: 'Sentence word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sentence_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentence_words/1
  # DELETE /sentence_words/1.json
  def destroy
    @sentence_word = SentenceWord.find(params[:id])
    @sentence_word.destroy

    respond_to do |format|
      format.html { redirect_to sentence_words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sentence_words_helper.rb
module SentenceWordsHelper
end

app/views/sentence_words/_form.html.erb
<%= form_for(@sentence_word) do |f| %>
  <% if @sentence_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sentence_word.errors.count, "error") %> prohibited this sentence_word from being saved:</h2>

      <ul>
      <% @sentence_word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br />
    <%= f.text_field :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sentence_words/edit.html.erb
<h1>Editing sentence_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @sentence_word %> |
<%= link_to 'Back', sentence_words_path %>

app/views/sentence_words/index.html.erb
<h1>Listing sentence_words</h1>

<table>
  <tr>
    <th>Position</th>
    <th>Word</th>
    <th>Sentence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sentence_words.each do |sentence_word| %>
  <tr>
    <td><%= sentence_word.position %></td>
    <td><%= sentence_word.word %></td>
    <td><%= sentence_word.sentence %></td>
    <td><%= link_to 'Show', sentence_word %></td>
    <td><%= link_to 'Edit', edit_sentence_word_path(sentence_word) %></td>
    <td><%= link_to 'Destroy', sentence_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sentence word', new_sentence_word_path %>

app/views/sentence_words/new.html.erb
<h1>New sentence_word</h1>

<%= render 'form' %>

<%= link_to 'Back', sentence_words_path %>

app/views/sentence_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @sentence_word.position %>
</p>

<p>
  <b>Word:</b>
  <%= @sentence_word.word %>
</p>

<p>
  <b>Sentence:</b>
  <%= @sentence_word.sentence %>
</p>


<%= link_to 'Edit', edit_sentence_word_path(@sentence_word) %> |
<%= link_to 'Back', sentence_words_path %>