config/routes.rb
Synphony::Application.routes.draw do
  resources :api_keys

  namespace :api, defaults: { format: 'json' } do
    namespace :simplified do
      resource :login
      resources :projects
      resources :projects do
        resources :words
      end
    end

    namespace :v1 do
    end
  end

  resources :user_language_projects

  resources :language_projects

  resources :language_projects do
    resources :user_spelling_patterns
    resources :sequence_spelling_patterns
    resources :sequences
    resources :sentence_spelling_patterns
    resources :sentence_words
    resources :sentences
    resources :word_spelling_patterns
    resources :words
    resources :spelling_patterns
    resources :phonemes
    resources :graphemes
  end

  devise_for :users

  root :to => 'landing_page#index'

end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :language_project
  attr_accessible :body, :reference
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  # GET /sentences
  # GET /sentences.json
  def index
    @sentences = Sentence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sentences }
    end
  end

  # GET /sentences/1
  # GET /sentences/1.json
  def show
    @sentence = Sentence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sentence }
    end
  end

  # GET /sentences/new
  # GET /sentences/new.json
  def new
    @sentence = Sentence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sentence }
    end
  end

  # GET /sentences/1/edit
  def edit
    @sentence = Sentence.find(params[:id])
  end

  # POST /sentences
  # POST /sentences.json
  def create
    @sentence = Sentence.new(params[:sentence])

    respond_to do |format|
      if @sentence.save
        format.html { redirect_to @sentence, notice: 'Sentence was successfully created.' }
        format.json { render json: @sentence, status: :created, location: @sentence }
      else
        format.html { render action: "new" }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sentences/1
  # PUT /sentences/1.json
  def update
    @sentence = Sentence.find(params[:id])

    respond_to do |format|
      if @sentence.update_attributes(params[:sentence])
        format.html { redirect_to @sentence, notice: 'Sentence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentences/1
  # DELETE /sentences/1.json
  def destroy
    @sentence = Sentence.find(params[:id])
    @sentence.destroy

    respond_to do |format|
      format.html { redirect_to sentences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/sentences/_form.html.erb
<%= form_for(@sentence) do |f| %>
  <% if @sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
      <% @sentence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language_project %><br />
    <%= f.text_field :language_project %>
  </div>
  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sentences/edit.html.erb
<h1>Editing sentence</h1>

<%= render 'form' %>

<%= link_to 'Show', @sentence %> |
<%= link_to 'Back', sentences_path %>

app/views/sentences/index.html.erb
<h1>Listing sentences</h1>

<table>
  <tr>
    <th>Language project</th>
    <th>Reference</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sentences.each do |sentence| %>
  <tr>
    <td><%= sentence.language_project %></td>
    <td><%= sentence.reference %></td>
    <td><%= sentence.body %></td>
    <td><%= link_to 'Show', sentence %></td>
    <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
    <td><%= link_to 'Destroy', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sentence', new_sentence_path %>

app/views/sentences/new.html.erb
<h1>New sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', sentences_path %>

app/views/sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Language project:</b>
  <%= @sentence.language_project %>
</p>

<p>
  <b>Reference:</b>
  <%= @sentence.reference %>
</p>

<p>
  <b>Body:</b>
  <%= @sentence.body %>
</p>


<%= link_to 'Edit', edit_sentence_path(@sentence) %> |
<%= link_to 'Back', sentences_path %>