config/routes.rb
Synphony::Application.routes.draw do
  resources :api_keys

  namespace :api, defaults: { format: 'json' } do
    namespace :simplified do
      resource :login
      resources :projects
      resources :projects do
        resources :words
      end
    end

    namespace :v1 do
    end
  end

  resources :user_language_projects

  resources :language_projects

  resources :language_projects do
    resources :user_spelling_patterns
    resources :sequence_spelling_patterns
    resources :sequences
    resources :sentence_spelling_patterns
    resources :sentence_words
    resources :sentences
    resources :word_spelling_patterns
    resources :words
    resources :spelling_patterns
    resources :phonemes
    resources :graphemes
  end

  devise_for :users

  root :to => 'landing_page#index'

end

app/models/phoneme.rb
class Phoneme < ActiveRecord::Base
  belongs_to :language_project
  attr_accessible :category, :ipa, :name, :text_frequency, :word_frequency
end

app/controllers/phonemes_controller.rb
class PhonemesController < ApplicationController
  # GET /phonemes
  # GET /phonemes.json
  def index
    @phonemes = Phoneme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phonemes }
    end
  end

  # GET /phonemes/1
  # GET /phonemes/1.json
  def show
    @phoneme = Phoneme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phoneme }
    end
  end

  # GET /phonemes/new
  # GET /phonemes/new.json
  def new
    @phoneme = Phoneme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phoneme }
    end
  end

  # GET /phonemes/1/edit
  def edit
    @phoneme = Phoneme.find(params[:id])
  end

  # POST /phonemes
  # POST /phonemes.json
  def create
    @phoneme = Phoneme.new(params[:phoneme])

    respond_to do |format|
      if @phoneme.save
        format.html { redirect_to @phoneme, notice: 'Phoneme was successfully created.' }
        format.json { render json: @phoneme, status: :created, location: @phoneme }
      else
        format.html { render action: "new" }
        format.json { render json: @phoneme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phonemes/1
  # PUT /phonemes/1.json
  def update
    @phoneme = Phoneme.find(params[:id])

    respond_to do |format|
      if @phoneme.update_attributes(params[:phoneme])
        format.html { redirect_to @phoneme, notice: 'Phoneme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phoneme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonemes/1
  # DELETE /phonemes/1.json
  def destroy
    @phoneme = Phoneme.find(params[:id])
    @phoneme.destroy

    respond_to do |format|
      format.html { redirect_to phonemes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/phonemes_helper.rb
module PhonemesHelper
end

app/views/phonemes/_form.html.erb
<%= form_for(@phoneme) do |f| %>
  <% if @phoneme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phoneme.errors.count, "error") %> prohibited this phoneme from being saved:</h2>

      <ul>
      <% @phoneme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language_project %><br />
    <%= f.text_field :language_project %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ipa %><br />
    <%= f.text_field :ipa %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :word_frequency %><br />
    <%= f.number_field :word_frequency %>
  </div>
  <div class="field">
    <%= f.label :text_frequency %><br />
    <%= f.number_field :text_frequency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phonemes/edit.html.erb
<h1>Editing phoneme</h1>

<%= render 'form' %>

<%= link_to 'Show', @phoneme %> |
<%= link_to 'Back', phonemes_path %>

app/views/phonemes/index.html.erb
<h1>Listing phonemes</h1>

<table>
  <tr>
    <th>Language project</th>
    <th>Name</th>
    <th>Ipa</th>
    <th>Category</th>
    <th>Word frequency</th>
    <th>Text frequency</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phonemes.each do |phoneme| %>
  <tr>
    <td><%= phoneme.language_project %></td>
    <td><%= phoneme.name %></td>
    <td><%= phoneme.ipa %></td>
    <td><%= phoneme.category %></td>
    <td><%= phoneme.word_frequency %></td>
    <td><%= phoneme.text_frequency %></td>
    <td><%= link_to 'Show', phoneme %></td>
    <td><%= link_to 'Edit', edit_phoneme_path(phoneme) %></td>
    <td><%= link_to 'Destroy', phoneme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phoneme', new_phoneme_path %>

app/views/phonemes/new.html.erb
<h1>New phoneme</h1>

<%= render 'form' %>

<%= link_to 'Back', phonemes_path %>

app/views/phonemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Language project:</b>
  <%= @phoneme.language_project %>
</p>

<p>
  <b>Name:</b>
  <%= @phoneme.name %>
</p>

<p>
  <b>Ipa:</b>
  <%= @phoneme.ipa %>
</p>

<p>
  <b>Category:</b>
  <%= @phoneme.category %>
</p>

<p>
  <b>Word frequency:</b>
  <%= @phoneme.word_frequency %>
</p>

<p>
  <b>Text frequency:</b>
  <%= @phoneme.text_frequency %>
</p>


<%= link_to 'Edit', edit_phoneme_path(@phoneme) %> |
<%= link_to 'Back', phonemes_path %>