config/routes.rb
Synphony::Application.routes.draw do
  resources :api_keys

  namespace :api, defaults: { format: 'json' } do
    namespace :simplified do
      resource :login
      resources :projects
      resources :projects do
        resources :words
      end
    end

    namespace :v1 do
    end
  end

  resources :user_language_projects

  resources :language_projects

  resources :language_projects do
    resources :user_spelling_patterns
    resources :sequence_spelling_patterns
    resources :sequences
    resources :sentence_spelling_patterns
    resources :sentence_words
    resources :sentences
    resources :word_spelling_patterns
    resources :words
    resources :spelling_patterns
    resources :phonemes
    resources :graphemes
  end

  devise_for :users

  root :to => 'landing_page#index'

end

app/models/user_spelling_pattern.rb
class UserSpellingPattern < ActiveRecord::Base
  belongs_to :user
  belongs_to :spelling_pattern
  belongs_to :language_project
  attr_accessible :focus, :position, :spelling_pattern_id, :language_project_id

  delegate :words, to: :spelling_pattern
end

app/controllers/user_spelling_patterns_controller.rb
class UserSpellingPatternsController < ApplicationController
  # GET /user_spelling_patterns
  # GET /user_spelling_patterns.json
  def index
    @user_spelling_patterns = @language_project.user_spelling_patterns.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_spelling_patterns }
    end
  end

  # GET /user_spelling_patterns/1
  # GET /user_spelling_patterns/1.json
  def show
    @user_spelling_pattern = @language_project.user_spelling_patterns.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_spelling_pattern }
    end
  end

  # GET /user_spelling_patterns/new
  # GET /user_spelling_patterns/new.json
  def new
    @user_spelling_pattern = @language_project.user_spelling_patterns.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_spelling_pattern }
    end
  end

  # GET /user_spelling_patterns/1/edit
  def edit
    @user_spelling_pattern = @language_project.user_spelling_patterns.find(params[:id])
  end

  # POST /user_spelling_patterns
  # POST /user_spelling_patterns.json
  def create
    @user_spelling_pattern = @language_project.user_spelling_patterns.build(params[:user_spelling_pattern])
    @user_spelling_pattern.user = current_user
    respond_to do |format|
      if @user_spelling_pattern.save
        format.html { redirect_to [@language_project, @user_spelling_pattern], notice: 'User spelling pattern was successfully created.' }
        format.json { render json: @user_spelling_pattern, status: :created, location: @user_spelling_pattern }
      else
        format.html { render action: "new" }
        format.json { render json: @user_spelling_pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_spelling_patterns/1
  # PUT /user_spelling_patterns/1.json
  def update
    @user_spelling_pattern = @language_project.user_spelling_patterns.find(params[:id])

    respond_to do |format|
      if @user_spelling_pattern.update_attributes(params[:user_spelling_pattern])
        format.html { redirect_to @user_spelling_pattern, notice: 'User spelling pattern was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_spelling_pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_spelling_patterns/1
  # DELETE /user_spelling_patterns/1.json
  def destroy
    @user_spelling_pattern = @language_project.user_spelling_patterns.find(params[:id])
    @user_spelling_pattern.destroy

    respond_to do |format|
      format.html { redirect_to user_spelling_patterns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_spelling_patterns_helper.rb
module UserSpellingPatternsHelper
end

app/views/user_spelling_patterns/_form.html.erb
<%= simple_form_for([@language_project, @user_spelling_pattern]) do |f| %>
  <% if @user_spelling_pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_spelling_pattern.errors.count, "error") %> prohibited this user_spelling_pattern from being saved:</h2>

      <ul>
      <% @user_spelling_pattern.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :position %>
  <%= f.association :spelling_pattern, :collection => @language_project.spelling_patterns %>
  <%= f.input :focus %>
  <%= f.button :submit %>
<% end %>

app/views/user_spelling_patterns/edit.html.erb
<h1>Editing user_spelling_pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', [@language_project, @user_spelling_pattern] %> |
<%= link_to 'Back', language_project_user_spelling_patterns_path(@language_project) %>

app/views/user_spelling_patterns/index.html.erb
<h1>Listing user_spelling_patterns</h1>

<table>
  <tr>
    <th>Position</th>
    <th>Spelling pattern</th>
    <th>Focus</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_spelling_patterns.each do |user_spelling_pattern| %>
  <tr>
    <td><%= user_spelling_pattern.position %></td>
    <td><%= user_spelling_pattern.spelling_pattern.name %></td>
    <td><%= user_spelling_pattern.focus %></td>
    <td><%= link_to 'Show', [@language_project, user_spelling_pattern] %></td>
    <td><%= link_to 'Edit', edit_language_project_user_spelling_pattern_path(@language_project, user_spelling_pattern) %></td>
    <td><%= link_to 'Destroy', [@language_project, user_spelling_pattern], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User spelling pattern', new_language_project_user_spelling_pattern_path(@language_project) %>

app/views/user_spelling_patterns/new.html.erb
<h1>New user_spelling_pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', language_project_user_spelling_patterns_path(@language_project) %>

app/views/user_spelling_patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @user_spelling_pattern.position %>
</p>

<p>
  <b>User:</b>
  <%= @user_spelling_pattern.user %>
</p>

<p>
  <b>Spelling pattern:</b>
  <%= @user_spelling_pattern.spelling_pattern %>
</p>

<p>
  <b>Focus:</b>
  <%= @user_spelling_pattern.focus %>
</p>


<%= link_to 'Edit', edit_language_project_user_spelling_pattern_path(@language_project, @user_spelling_pattern) %> |
<%= link_to 'Back', language_project_user_spelling_patterns_path(@language_project) %>